import { Card, Slide, Poster, AISoftware, CartItem } from '@/types';

// Mock data for intro/outro cards
export const introOutroCards: Card[] = [
  {
    id: '1',
    title: 'Triết học',
    href: '/slide/triet-hoc-1',
  },
  {
    id: '2',
    title: 'Triết học 2',
    href: '/slide/triet-hoc-2',
  },
  {
    id: '3',
    title: '20/11',
    href: '/slide/20-11',
  },
  {
    id: '4',
    title: 'Triết học',
    href: '/slide/triet-hoc',
  },
  {
    id: '5',
    title: 'TIEU DE',
    href: '/slide/tieu-de',
  },
  {
    id: '6',
    title: 'MT',
    href: '/slide/mt',
  },
];

// Mock data for slides
export const morphSlides: Slide[] = [
  {
    id: '1',
    title: 'Slide Phạm Trù Triết Học',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/slide/pham-tru-triet-hoc-1',
  },
  {
    id: '2',
    title: 'Slide Phạm Trù Triết Học',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/slide/pham-tru-triet-hoc-2',
  },
  {
    id: '3',
    title: 'Slide Phạm Trù Triết Học',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/slide/pham-tru-triet-hoc-3',
  },
  {
    id: '4',
    title: 'Slide Phạm Trù Triết Học',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/slide/pham-tru-triet-hoc-4',
  },
];

// Mock data for featured slides
export const featuredSlides: Slide[] = [
  {
    id: 'f1',
    title: 'Slide Đinh Bộ Lĩnh',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9912,
    downloads: 2351,
    href: '/slide/dinh-bo-linh',
  },
  {
    id: 'f2',
    title: 'Slide Phạm Trù Triết Học',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/slide/pham-tru-triet-hoc-featured',
  },
  {
    id: 'f3',
    title: 'Slide Giới Thiệu Việt Nam',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9903,
    downloads: 2891,
    href: '/slide/gioi-thieu-viet-nam',
  },
  {
    id: 'f4',
    title: 'Slide Phạm Trù Triết Học',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/slide/pham-tru-triet-hoc-2-featured',
  },
  {
    id: 'f5',
    title: 'Slide Giới Thiệu Việt Nam',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9903,
    downloads: 2891,
    href: '/slide/gioi-thieu-viet-nam-2',
  },
  {
    id: 'f6',
    title: 'Slide Phân Tích Quan Điểm Hồ Chí Minh',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9903,
    downloads: 2891,
    href: '/slide/phan-tich-quan-diem-ho-chi-minh',
  },
  {
    id: 'f7',
    title: 'Slide Mối Quan Hệ Biện Chứng Giữa Tồn Tại Và Ý Thức Xã Hội',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8756,
    downloads: 2134,
    href: '/slide/moi-quan-he-bien-chung',
  },
  {
    id: 'f8',
    title: 'Slide Giới Thiệu Dân Tộc Chăm',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 12345,
    downloads: 3456,
    href: '/slide/gioi-thieu-dan-toc-cham',
  },
  {
    id: 'f9',
    title: 'Slide Bánh Chưng & Bánh Tét',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/slide/banh-chung-banh-tet',
  },
];

// Mock data for animations
export const animations: Slide[] = [
  {
    id: 'a1',
    title: 'Bộ nhân vật SGK',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9912,
    downloads: 2351,
    href: '/hoat-hinh/nhan-vat-sgk',
  },
  {
    id: 'a2',
    title: 'Bộ nhân vật Động vật',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8756,
    downloads: 2134,
    href: '/hoat-hinh/nhan-vat-dong-vat',
  },
  {
    id: 'a3',
    title: 'Bộ nhân vật BabyThree và Labubu',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 12345,
    downloads: 3456,
    href: '/hoat-hinh/babythree-labubu',
    isFree: true,
  },
  {
    id: 'a4',
    title: 'Bộ nhân vật BabyThree và Labubu',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 11234,
    downloads: 2987,
    href: '/hoat-hinh/babythree-labubu-2',
    isFree: true,
  },
  {
    id: 'a5',
    title: 'Bộ nhân vật Động vật',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9876,
    downloads: 2345,
    href: '/hoat-hinh/nhan-vat-dong-vat-2',
  },
  {
    id: 'a6',
    title: 'Bộ nhân vật Trung Quốc',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8567,
    downloads: 1987,
    href: '/hoat-hinh/nhan-vat-trung-quoc',
  },
  {
    id: 'a7',
    title: 'Bộ nhân vật BabyThree và Labubu',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 10987,
    downloads: 3123,
    href: '/hoat-hinh/babythree-labubu-3',
    isFree: true,
  },
  {
    id: 'a8',
    title: 'Bộ nhân vật BabyThree và Labubu',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 10123,
    downloads: 2876,
    href: '/hoat-hinh/babythree-labubu-4',
    isFree: true,
  },
];

// Mock data for posters
export const topRowPosters: Poster[] = [
  {
    id: 'p1',
    href: '/poster/giang-sinh-1',
    category: 'Giáng sinh',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9912,
    downloads: 2351,
  },
  {
    id: 'p2',
    href: '/poster/giang-sinh-2',
    category: 'Giáng sinh',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9912,
    downloads: 2351,
  },
  {
    id: 'p3',
    href: '/poster/giang-sinh-3',
    category: 'Giáng sinh',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9912,
    downloads: 2351,
  },
];

export const bottomRowPosters: Poster[] = [
  {
    id: 'p4',
    href: '/poster/giang-sinh-4',
    category: 'Giáng sinh',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9912,
    downloads: 2351,
  },
  {
    id: 'p5',
    href: '/poster/giang-sinh-5',
    category: 'Giáng sinh',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9912,
    downloads: 2351,
  },
  {
    id: 'p6',
    href: '/poster/giang-sinh-6',
    category: 'Giáng sinh',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9912,
    downloads: 2351,
  },
  {
    id: 'p7',
    href: '/poster/giang-sinh-7',
    category: 'Giáng sinh',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9912,
    downloads: 2351,
  },
];

// Helper function to add pricing and stats to poster
const addPosterData = (poster: Omit<Poster, 'originalPrice' | 'discountedPrice' | 'discountPercent' | 'views' | 'downloads'>): Poster => ({
  ...poster,
  originalPrice: 69000,
  discountedPrice: 49000,
  discountPercent: 29,
  views: 9912,
  downloads: 2351,
});

// All posters for the poster page
export const allPosters: Poster[] = [
  // Giáng sinh
  ...topRowPosters,
  ...bottomRowPosters,
  addPosterData({
    id: 'p8',
    href: '/poster/giang-sinh-8',
    category: 'Giáng sinh',
  }),
  addPosterData({
    id: 'p9',
    href: '/poster/giang-sinh-9',
    category: 'Giáng sinh',
  }),
  addPosterData({
    id: 'p10',
    href: '/poster/giang-sinh-10',
    category: 'Giáng sinh',
  }),
  addPosterData({
    id: 'p11',
    href: '/poster/giang-sinh-11',
    category: 'Giáng sinh',
  }),
  addPosterData({
    id: 'p12',
    href: '/poster/giang-sinh-12',
    category: 'Giáng sinh',
  }),
  // Tết
  addPosterData({
    id: 'p13',
    href: '/poster/tet-1',
    category: 'Tết',
  }),
  addPosterData({
    id: 'p14',
    href: '/poster/tet-2',
    category: 'Tết',
  }),
  addPosterData({
    id: 'p15',
    href: '/poster/tet-3',
    category: 'Tết',
  }),
  addPosterData({
    id: 'p16',
    href: '/poster/tet-4',
    category: 'Tết',
  }),
  addPosterData({
    id: 'p17',
    href: '/poster/tet-5',
    category: 'Tết',
  }),
  addPosterData({
    id: 'p18',
    href: '/poster/tet-6',
    category: 'Tết',
  }),
  addPosterData({
    id: 'p19',
    href: '/poster/tet-7',
    category: 'Tết',
  }),
  addPosterData({
    id: 'p20',
    href: '/poster/tet-8',
    category: 'Tết',
  }),
  // 20/10
  addPosterData({
    id: 'p21',
    href: '/poster/20-10-1',
    category: '20/10',
  }),
  addPosterData({
    id: 'p22',
    href: '/poster/20-10-2',
    category: '20/10',
  }),
  addPosterData({
    id: 'p23',
    href: '/poster/20-10-3',
    category: '20/10',
  }),
  addPosterData({
    id: 'p24',
    href: '/poster/20-10-4',
    category: '20/10',
  }),
  addPosterData({
    id: 'p25',
    href: '/poster/20-10-5',
    category: '20/10',
  }),
  addPosterData({
    id: 'p26',
    href: '/poster/20-10-6',
    category: '20/10',
  }),
  addPosterData({
    id: 'p27',
    href: '/poster/20-10-7',
    category: '20/10',
  }),
  addPosterData({
    id: 'p28',
    href: '/poster/20-10-8',
    category: '20/10',
  }),
  // 20/11
  addPosterData({
    id: 'p29',
    href: '/poster/20-11-1',
    category: '20/11',
  }),
  addPosterData({
    id: 'p30',
    href: '/poster/20-11-2',
    category: '20/11',
  }),
  addPosterData({
    id: 'p31',
    href: '/poster/20-11-3',
    category: '20/11',
  }),
  addPosterData({
    id: 'p32',
    href: '/poster/20-11-4',
    category: '20/11',
  }),
  addPosterData({
    id: 'p33',
    href: '/poster/20-11-5',
    category: '20/11',
  }),
  addPosterData({
    id: 'p34',
    href: '/poster/20-11-6',
    category: '20/11',
  }),
  addPosterData({
    id: 'p35',
    href: '/poster/20-11-7',
    category: '20/11',
  }),
  addPosterData({
    id: 'p36',
    href: '/poster/20-11-8',
    category: '20/11',
  }),
  // 8/3
  addPosterData({
    id: 'p37',
    href: '/poster/8-3-1',
    category: '8/3',
  }),
  addPosterData({
    id: 'p38',
    href: '/poster/8-3-2',
    category: '8/3',
  }),
  addPosterData({
    id: 'p39',
    href: '/poster/8-3-3',
    category: '8/3',
  }),
  addPosterData({
    id: 'p40',
    href: '/poster/8-3-4',
    category: '8/3',
  }),
  addPosterData({
    id: 'p41',
    href: '/poster/8-3-5',
    category: '8/3',
  }),
  addPosterData({
    id: 'p42',
    href: '/poster/8-3-6',
    category: '8/3',
  }),
  addPosterData({
    id: 'p43',
    href: '/poster/8-3-7',
    category: '8/3',
  }),
  addPosterData({
    id: 'p44',
    href: '/poster/8-3-8',
    category: '8/3',
  }),
  // Trung thu
  addPosterData({
    id: 'p45',
    href: '/poster/trung-thu-1',
    category: 'Trung thu',
  }),
  addPosterData({
    id: 'p46',
    href: '/poster/trung-thu-2',
    category: 'Trung thu',
  }),
  addPosterData({
    id: 'p47',
    href: '/poster/trung-thu-3',
    category: 'Trung thu',
  }),
  addPosterData({
    id: 'p48',
    href: '/poster/trung-thu-4',
    category: 'Trung thu',
  }),
  addPosterData({
    id: 'p49',
    href: '/poster/trung-thu-5',
    category: 'Trung thu',
  }),
  addPosterData({
    id: 'p50',
    href: '/poster/trung-thu-6',
    category: 'Trung thu',
  }),
  addPosterData({
    id: 'p51',
    href: '/poster/trung-thu-7',
    category: 'Trung thu',
  }),
  addPosterData({
    id: 'p52',
    href: '/poster/trung-thu-8',
    category: 'Trung thu',
  }),
  // Quốc Khánh
  addPosterData({
    id: 'p53',
    href: '/poster/quoc-khanh-1',
    category: 'Quốc Khánh',
  }),
  addPosterData({
    id: 'p54',
    href: '/poster/quoc-khanh-2',
    category: 'Quốc Khánh',
  }),
  addPosterData({
    id: 'p55',
    href: '/poster/quoc-khanh-3',
    category: 'Quốc Khánh',
  }),
  addPosterData({
    id: 'p56',
    href: '/poster/quoc-khanh-4',
    category: 'Quốc Khánh',
  }),
  addPosterData({
    id: 'p57',
    href: '/poster/quoc-khanh-5',
    category: 'Quốc Khánh',
  }),
  addPosterData({
    id: 'p58',
    href: '/poster/quoc-khanh-6',
    category: 'Quốc Khánh',
  }),
  addPosterData({
    id: 'p59',
    href: '/poster/quoc-khanh-7',
    category: 'Quốc Khánh',
  }),
  addPosterData({
    id: 'p60',
    href: '/poster/quoc-khanh-8',
    category: 'Quốc Khánh',
  }),
  // Giỗ tổ Hùng Vương
  addPosterData({
    id: 'p61',
    href: '/poster/gio-to-hung-vuong-1',
    category: 'Giỗ tổ Hùng Vương',
  }),
  addPosterData({
    id: 'p62',
    href: '/poster/gio-to-hung-vuong-2',
    category: 'Giỗ tổ Hùng Vương',
  }),
  addPosterData({
    id: 'p63',
    href: '/poster/gio-to-hung-vuong-3',
    category: 'Giỗ tổ Hùng Vương',
  }),
  addPosterData({
    id: 'p64',
    href: '/poster/gio-to-hung-vuong-4',
    category: 'Giỗ tổ Hùng Vương',
  }),
  addPosterData({
    id: 'p65',
    href: '/poster/gio-to-hung-vuong-5',
    category: 'Giỗ tổ Hùng Vương',
  }),
  addPosterData({
    id: 'p66',
    href: '/poster/gio-to-hung-vuong-6',
    category: 'Giỗ tổ Hùng Vương',
  }),
  addPosterData({
    id: 'p67',
    href: '/poster/gio-to-hung-vuong-7',
    category: 'Giỗ tổ Hùng Vương',
  }),
  addPosterData({
    id: 'p68',
    href: '/poster/gio-to-hung-vuong-8',
    category: 'Giỗ tổ Hùng Vương',
  }),
];

// Mock data for AI Software
export const aiSoftwareProducts: AISoftware[] = [
  {
    id: 'ai1',
    title: 'Tài khoản Canva Pro - 2 năm',
    originalPrice: 249000,
    discountedPrice: 199000,
    discountPercent: 20,
    views: 5866,
    downloads: 2351,
    href: '/tai-khoan-ai/canva-pro-2-nam',
  },
  {
    id: 'ai2',
    title: 'Tài khoản Canva Pro - 1 năm',
    originalPrice: 159000,
    discountedPrice: 119000,
    discountPercent: 25,
    views: 7158,
    downloads: 2891,
    href: '/tai-khoan-ai/canva-pro-1-nam',
  },
  {
    id: 'ai3',
    title: 'Tài khoản Canva Pro - 1 tháng',
    originalPrice: 35000,
    discountedPrice: 19000,
    discountPercent: 46,
    views: 7286,
    downloads: 4528,
    href: '/tai-khoan-ai/canva-pro-1-thang',
  },
  {
    id: 'ai4',
    title: 'Tài khoản Animiz Animation Maker',
    originalPrice: 249000,
    discountedPrice: 199000,
    discountPercent: 20,
    views: 5006,
    downloads: 2351,
    href: '/tai-khoan-ai/animiz',
  },
  {
    id: 'ai5',
    title: 'Tài khoản Capcut Pro - 1 năm',
    originalPrice: 159000,
    discountedPrice: 119000,
    discountPercent: 25,
    views: 7158,
    downloads: 2891,
    href: '/tai-khoan-ai/capcut-pro-1-nam',
  },
  {
    id: 'ai6',
    title: 'Tài khoản Capcut Pro - 1 tháng',
    originalPrice: 35000,
    discountedPrice: 19000,
    discountPercent: 46,
    views: 7200,
    downloads: 4528,
    href: '/tai-khoan-ai/capcut-pro-1-thang',
  },
  {
    id: 'ai7',
    title: 'Tài khoản Adobe Creative Cloud - 1 năm',
    originalPrice: 299000,
    discountedPrice: 249000,
    discountPercent: 17,
    views: 6234,
    downloads: 1987,
    href: '/tai-khoan-ai/adobe-cc-1-nam',
  },
  {
    id: 'ai8',
    title: 'Tài khoản Adobe Creative Cloud - 1 tháng',
    originalPrice: 45000,
    discountedPrice: 29000,
    discountPercent: 36,
    views: 5678,
    downloads: 2345,
    href: '/tai-khoan-ai/adobe-cc-1-thang',
  },
  {
    id: 'ai9',
    title: 'Tài khoản Figma Pro - 1 năm',
    originalPrice: 199000,
    discountedPrice: 149000,
    discountPercent: 25,
    views: 4890,
    downloads: 1678,
    href: '/tai-khoan-ai/figma-pro-1-nam',
  },
  {
    id: 'ai10',
    title: 'Tài khoản Figma Pro - 1 tháng',
    originalPrice: 30000,
    discountedPrice: 19000,
    discountPercent: 37,
    views: 5123,
    downloads: 1892,
    href: '/tai-khoan-ai/figma-pro-1-thang',
  },
  {
    id: 'ai11',
    title: 'Tài khoản Notion Pro - 1 năm',
    originalPrice: 149000,
    discountedPrice: 99000,
    discountPercent: 34,
    views: 4567,
    downloads: 1456,
    href: '/tai-khoan-ai/notion-pro-1-nam',
  },
  {
    id: 'ai12',
    title: 'Tài khoản Notion Pro - 1 tháng',
    originalPrice: 25000,
    discountedPrice: 15000,
    discountPercent: 40,
    views: 4321,
    downloads: 1234,
    href: '/tai-khoan-ai/notion-pro-1-thang',
  },
  {
    id: 'ai13',
    title: 'Tài khoản Midjourney Pro - 1 năm',
    originalPrice: 399000,
    discountedPrice: 299000,
    discountPercent: 25,
    views: 6789,
    downloads: 2567,
    href: '/tai-khoan-ai/midjourney-pro-1-nam',
  },
  {
    id: 'ai14',
    title: 'Tài khoản Midjourney Pro - 1 tháng',
    originalPrice: 50000,
    discountedPrice: 35000,
    discountPercent: 30,
    views: 5432,
    downloads: 1987,
    href: '/tai-khoan-ai/midjourney-pro-1-thang',
  },
];

// Mock data for Intro/Outro page
export const introOutroSlides: Slide[] = [
  {
    id: 'intro-1',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 12345,
    downloads: 5678,
    href: '/slide/gioi-thieu-thanh-vien-1',
  },
  {
    id: 'intro-2',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 11234,
    downloads: 5234,
    href: '/slide/gioi-thieu-thanh-vien-2',
  },
  {
    id: 'intro-3',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 10987,
    downloads: 5123,
    href: '/slide/gioi-thieu-thanh-vien-3',
  },
  {
    id: 'intro-4',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9876,
    downloads: 4567,
    href: '/slide/bao-luc-gia-dinh-1',
  },
  {
    id: 'intro-5',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9654,
    downloads: 4456,
    href: '/slide/bao-luc-gia-dinh-2',
  },
  {
    id: 'intro-6',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9432,
    downloads: 4345,
    href: '/slide/bao-luc-hoc-duong-1',
  },
  {
    id: 'intro-7',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9210,
    downloads: 4234,
    href: '/slide/bao-luc-gia-dinh-3',
  },
  {
    id: 'intro-8',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8988,
    downloads: 4123,
    href: '/slide/bao-luc-hoc-duong-2',
  },
  {
    id: 'intro-9',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8766,
    downloads: 4012,
    href: '/slide/bao-luc-gia-dinh-4',
  },
  {
    id: 'intro-10',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8544,
    downloads: 3901,
    href: '/slide/gioi-thieu-thanh-vien-4',
  },
  {
    id: 'intro-11',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8322,
    downloads: 3790,
    href: '/slide/bao-luc-hoc-duong-3',
  },
  {
    id: 'intro-12',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8100,
    downloads: 3679,
    href: '/slide/gioi-thieu-thanh-vien-5',
  },
  {
    id: 'intro-13',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 7878,
    downloads: 3568,
    href: '/slide/bao-luc-gia-dinh-5',
  },
  {
    id: 'intro-14',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 7656,
    downloads: 3457,
    href: '/slide/bao-luc-hoc-duong-4',
  },
  {
    id: 'intro-15',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 7434,
    downloads: 3346,
    href: '/slide/gioi-thieu-thanh-vien-6',
  },
];

// Mock data for Video categories
export const giaoDucVideos: Slide[] = [
  {
    id: 'video-gd-1',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-1',
  },
  {
    id: 'video-gd-2',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-2',
  },
  {
    id: 'video-gd-3',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-3',
  },
  {
    id: 'video-gd-4',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-4',
  },
  {
    id: 'video-gd-5',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-5',
  },
  {
    id: 'video-gd-6',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-6',
  },
  {
    id: 'video-gd-7',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-7',
  },
  {
    id: 'video-gd-8',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-8',
  },
  {
    id: 'video-gd-9',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-9',
  },
  {
    id: 'video-gd-10',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-10',
  },
  {
    id: 'video-gd-11',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-11',
  },
  {
    id: 'video-gd-12',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-12',
  },
  {
    id: 'video-gd-13',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/gioi-thieu-thanh-vien-13',
  },
];

export const daiCuongVideos: Slide[] = [
  {
    id: 'video-dc-1',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-1',
  },
  {
    id: 'video-dc-2',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-2',
  },
  {
    id: 'video-dc-3',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-3',
  },
  {
    id: 'video-dc-4',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-4',
  },
  {
    id: 'video-dc-5',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-5',
  },
  {
    id: 'video-dc-6',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-6',
  },
  {
    id: 'video-dc-7',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-7',
  },
  {
    id: 'video-dc-8',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-8',
  },
  {
    id: 'video-dc-9',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-9',
  },
  {
    id: 'video-dc-10',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-10',
  },
  {
    id: 'video-dc-11',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-11',
  },
  {
    id: 'video-dc-12',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-12',
  },
  {
    id: 'video-dc-13',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/dai-cuong-13',
  },
];

export const ngayLeSuKienVideos: Slide[] = [
  {
    id: 'video-nl-1',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-1',
  },
  {
    id: 'video-nl-2',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-2',
  },
  {
    id: 'video-nl-3',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-3',
  },
  {
    id: 'video-nl-4',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-4',
  },
  {
    id: 'video-nl-5',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-5',
  },
  {
    id: 'video-nl-6',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-6',
  },
  {
    id: 'video-nl-7',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-7',
  },
  {
    id: 'video-nl-8',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-8',
  },
  {
    id: 'video-nl-9',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-9',
  },
  {
    id: 'video-nl-10',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-10',
  },
  {
    id: 'video-nl-11',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-11',
  },
  {
    id: 'video-nl-12',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-12',
  },
  {
    id: 'video-nl-13',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 9871,
    downloads: 4528,
    href: '/video/ngay-le-13',
  },
];

// Mock data for Slide categories
export const gioiThieuThanhVienSlides: Slide[] = [
  {
    id: 'slide-gttv-1',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-1',
  },
  {
    id: 'slide-gttv-2',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-2',
  },
  {
    id: 'slide-gttv-3',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-3',
  },
  {
    id: 'slide-gttv-4',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-4',
  },
  {
    id: 'slide-gttv-5',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-5',
  },
  {
    id: 'slide-gttv-6',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-6',
  },
  {
    id: 'slide-gttv-7',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-7',
  },
  {
    id: 'slide-gttv-8',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-8',
  },
  {
    id: 'slide-gttv-9',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-9',
  },
  {
    id: 'slide-gttv-10',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-10',
  },
  {
    id: 'slide-gttv-11',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-11',
  },
  {
    id: 'slide-gttv-12',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-12',
  },
  {
    id: 'slide-gttv-13',
    title: 'Slide Giới Thiệu Thành Viên',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/gioi-thieu-thanh-vien-13',
  },
];

export const baoLucHocDuongSlides: Slide[] = [
  {
    id: 'slide-blhd-1',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-1',
  },
  {
    id: 'slide-blhd-2',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-2',
  },
  {
    id: 'slide-blhd-3',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-3',
  },
  {
    id: 'slide-blhd-4',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-4',
  },
  {
    id: 'slide-blhd-5',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-5',
  },
  {
    id: 'slide-blhd-6',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-6',
  },
  {
    id: 'slide-blhd-7',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-7',
  },
  {
    id: 'slide-blhd-8',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-8',
  },
  {
    id: 'slide-blhd-9',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-9',
  },
  {
    id: 'slide-blhd-10',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-10',
  },
  {
    id: 'slide-blhd-11',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-11',
  },
  {
    id: 'slide-blhd-12',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-12',
  },
  {
    id: 'slide-blhd-13',
    title: 'Slide Bạo Lực Học Đường',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-hoc-duong-13',
  },
];

export const baoLucGiaDinhSlides: Slide[] = [
  {
    id: 'slide-blgd-1',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-1',
  },
  {
    id: 'slide-blgd-2',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-2',
  },
  {
    id: 'slide-blgd-3',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-3',
  },
  {
    id: 'slide-blgd-4',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-4',
  },
  {
    id: 'slide-blgd-5',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-5',
  },
  {
    id: 'slide-blgd-6',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-6',
  },
  {
    id: 'slide-blgd-7',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-7',
  },
  {
    id: 'slide-blgd-8',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-8',
  },
  {
    id: 'slide-blgd-9',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-9',
  },
  {
    id: 'slide-blgd-10',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-10',
  },
  {
    id: 'slide-blgd-11',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-11',
  },
  {
    id: 'slide-blgd-12',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-12',
  },
  {
    id: 'slide-blgd-13',
    title: 'Slide Bạo Lực Gia Đình',
    originalPrice: 69000,
    discountedPrice: 49000,
    discountPercent: 29,
    views: 8671,
    downloads: 4528,
    href: '/slide/bao-luc-gia-dinh-13',
  },
];

// Mock data for free slides
export const freeSlides: Slide[] = [
  {
    id: 'free1',
    title: 'Tài khoản Canva Pro - 2 năm',
    originalPrice: 249000,
    discountedPrice: 0,
    discountPercent: 20,
    views: 5866,
    downloads: 2351,
    href: '/san-pham/canva-pro-2-nam',
    isFree: true,
    category: 'Graphic',
    image: '/images/slide-placeholder.png',
  },
  {
    id: 'free2',
    title: 'Tài khoản Canva Pro - 1 năm',
    originalPrice: 159000,
    discountedPrice: 0,
    discountPercent: 25,
    views: 7158,
    downloads: 2891,
    href: '/san-pham/canva-pro-1-nam',
    isFree: true,
    category: 'Template',
    image: '/images/slide-placeholder.png',
  },
  {
    id: 'free3',
    title: 'Tài khoản Canva Pro - 1 tháng',
    originalPrice: 35000,
    discountedPrice: 0,
    discountPercent: 46,
    views: 7286,
    downloads: 4528,
    href: '/san-pham/canva-pro-1-thang',
    isFree: true,
    category: 'Graphic',
    image: '/images/slide-placeholder.png',
  },
  {
    id: 'free4',
    title: 'Slide Template Miễn Phí 1',
    originalPrice: 69000,
    discountedPrice: 0,
    discountPercent: 100,
    views: 5234,
    downloads: 1892,
    href: '/san-pham/slide-template-free-1',
    isFree: true,
    category: 'Template',
    image: '/images/slide-placeholder.png',
  },
  {
    id: 'free5',
    title: 'Slide Template Miễn Phí 2',
    originalPrice: 69000,
    discountedPrice: 0,
    discountPercent: 100,
    views: 4123,
    downloads: 1567,
    href: '/san-pham/slide-template-free-2',
    isFree: true,
    category: 'Graphic',
    image: '/images/slide-placeholder.png',
  },
  {
    id: 'free6',
    title: 'Slide Template Miễn Phí 3',
    originalPrice: 69000,
    discountedPrice: 0,
    discountPercent: 100,
    views: 6789,
    downloads: 2345,
    href: '/san-pham/slide-template-free-3',
    isFree: true,
    category: 'Template',
    image: '/images/slide-placeholder.png',
  },
  {
    id: 'free7',
    title: 'Slide Template Miễn Phí 4',
    originalPrice: 69000,
    discountedPrice: 0,
    discountPercent: 100,
    views: 3456,
    downloads: 1234,
    href: '/san-pham/slide-template-free-4',
    isFree: true,
    category: 'Graphic',
    image: '/images/slide-placeholder.png',
  },
  {
    id: 'free8',
    title: 'Slide Template Miễn Phí 5',
    originalPrice: 69000,
    discountedPrice: 0,
    discountPercent: 100,
    views: 5678,
    downloads: 1987,
    href: '/san-pham/slide-template-free-5',
    isFree: true,
    category: 'Template',
    image: '/images/slide-placeholder.png',
  },
  {
    id: 'free9',
    title: 'Slide Template Miễn Phí 6',
    originalPrice: 69000,
    discountedPrice: 0,
    discountPercent: 100,
    views: 4321,
    downloads: 1456,
    href: '/san-pham/slide-template-free-6',
    isFree: true,
    category: 'Graphic',
    image: '/images/slide-placeholder.png',
  },
];

// Mock data for cart items
export const cartItems: CartItem[] = [
  {
    id: 'cart-1',
    productId: 'dan-toc-cham-1',
    title: 'Slide Dân Tộc Chăm',
    image: '/images/slide-placeholder.png',
    price: 59000,
    quantity: 1,
  },
  {
    id: 'cart-2',
    productId: 'dan-toc-cham-2',
    title: 'Slide Dân Tộc Chăm',
    image: '/images/slide-placeholder.png',
    price: 59000,
    quantity: 1,
  },
  {
    id: 'cart-3',
    productId: 'dan-toc-cham-3',
    title: 'Slide Dân Tộc Chăm',
    image: '/images/slide-placeholder.png',
    price: 59000,
    quantity: 1,
  },
  {
    id: 'cart-4',
    productId: 'dan-toc-cham-4',
    title: 'Slide Dân Tộc Chăm',
    image: '/images/slide-placeholder.png',
    price: 59000,
    quantity: 1,
  },
];

